# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install -y qemu-system
  displayName: "Install QEMU"
- script: packer --version
  displayName: "Check version of packer"
- script: echo $(System.DefaultWorkingDirectory)
  displayName: "Show $(System.DefaultWorkingDirectory)"
- script: |
    sudo mkdir -p $(System.DefaultWorkingDirectory)/shared
    sudo mkdir -p $(System.DefaultWorkingDirectory)/shared
  displayName: "Create packer tmp dirs"
- task: PackerBuild@1
  inputs:
    templateType: 'custom'
    customTemplateLocation: 'windows_10_enterprise_lite.json'
    customTemplateParameters: |
      {"output_directory": "$(System.DefaultWorkingDirectory)/shared/packer_tmp",
      "post_proc_output": "$(System.DefaultWorkingDirectory)/shared/packer_out"}
- publish: $(System.DefaultWorkingDirectory)/shared/packer_out/
  artifact: windows_10_ent

