# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: apt-get install -y qemu-system
  displayName: "Install QEMU"
- script: packer --version
  displayName: 'Check version of packer'
- task: PackerBuild@1
  inputs:
    templateType: 'custom'
    customTemplateLocation: 'windows_10_enterprise_lite.json'
    imageUri: 'output_directory'
